name: Deploy to Zama Sepolia

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Compile contracts
      run: npx hardhat compile

    - name: Deploy to Zama Sepolia
      run: npx hardhat run scripts/deploy.js --network sepolia
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ZAMA_RPC_URL: ${{ secrets.ZAMA_RPC_URL }}
